routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('login/github', 'Auth\LoginController@redirectToProvider')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');

Route::resource('products', 'ProductController');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');

        // $this->authorizeResource(Product::class, 'product');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', Product::class);

        // if (Gate::denies('viewAny', Product::class)) {
        //    return redirect('/');
        // }

        $products = Product::all();

        return view('products.index')->with(compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('create', Product::class)) {
            return redirect()->route('products.index');
        }

        return view('products.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Gate::denies('create', Product::class)) {
            return redirect()->route('products.index');
        }

        $data = $request->validate([
            'name' => ['required', 'between:1,255'],
            'price' => ['required', 'numeric', 'min:0'],
        ]);

        auth()->user()->products()->create($data);

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Entity\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        if (Gate::denies('view', $product)) {
            return redirect()->route('products.index');
        }

        return view('products.show')->with(compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Entity\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        if (Gate::denies('update', $product)) {
            return redirect()->route('products.index');
        }

        return view('products.edit')->with(compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entity\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        if (Gate::denies('update', $product)) {
            return redirect()->route('products.index');
        }

        $data = $request->validate([
            'name' => ['required', 'between:1,255'],
            'price' => ['required', 'numeric', 'min:0'],
        ]);

        $product->update($data);

        return redirect()->route('products.show', ['product' => $product]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Entity\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if (Gate::denies('delete', $product)) {
            return redirect()->route('products.index');
        }

        $product->delete();

        return redirect()->route('products.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('products.index') }}">{{ __('Products') }}</a>
                            </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/card.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@yield('header')</div>
                <div class="card-body">
                    @yield('body')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/add.blade.php
@extends('layouts.card')

@section('header', 'Add a new product')

@section('body')
<form id="add" method="POST" action="{{ route('products.store') }}">
    @csrf
    <div class="form-group">
        <label for="name">Name</label>
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Enter product name" value="{{ old('name') }}" required>
        @error('name')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input id="price" type="number" step="0.01" min="0" class="form-control @error('price') is-invalid @enderror" name="price" placeholder="Enter product price" value="{{ old('price') }}" required>
        @error('price')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror
    </div>
    <button type="submit" form="add" class="btn btn-primary btn-lg">Save</button>
</form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.card')

@section('header', 'Edit the product')

@section('body')
<form id="edit" method="POST" action="{{ route('products.update', ['product' => $product]) }}">
    @csrf
    @method('PATCH')
    <div class="form-group">
        <label for="name">Name</label>
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Enter product name" value="{{ $product->name }}" required>
        @error('name')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input id="price" type="number" step="0.01" min="0" class="form-control @error('price') is-invalid @enderror" name="price" placeholder="Enter product price" value="{{ $product->price }}" required>
        @error('price')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror
    </div>
    <button type="submit" form="edit" class="btn btn-primary btn-lg">Save</button>
    <button type="submit" form="delete" class="btn btn-danger btn-sm ml-4">Delete</button>
</form>

<form id="delete" method="POST" action="{{ route('products.destroy', ['product' => $product]) }}">
    @csrf
    @method('DELETE')
</form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.card')

@section('header', 'Products')

@section('body')
@if (session('status'))
<div class="alert alert-success" role="alert">
    {{ session('status') }}
</div>
@endif

@if ($products->isNotEmpty())
<table class="table table-striped table-sm">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Owner</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($products as $product)
        <tr>
            <th scope="row">{{ $product->id }}</th>
            <td>
                <a href="{{ route('products.show', ['product' => $product]) }}">{{ $product->name }}</a>
            </td>
            <td>{{ $product->price }}</td>
            <td>{{ $product->user->name }}</td>
            <td>
                @can('update', $product)
                <a class="btn btn-primary btn-sm"
                    href="{{ route('products.edit', ['product' => $product]) }}"
                    role="button">Edit</a>
                @endcan
                @can('delete', $product)
                <button type="submit" form="delete"
                    formaction="{{ route('products.destroy', ['product' => $product]) }}"
                    class="btn btn-danger btn-sm ml-4">Delete</button>
                @endcan
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

<form id="delete" method="POST">
    @csrf
    @method('DELETE')
</form>
@else
<p>No available products.</p>
@endif

<div class="row justify-content-center">
    <div class="col-md-6">
        <a class="btn btn-success btn-lg btn-block mt-2"
            href="{{ route('products.create') }}"
            role="button">Add</a>
    </div>
</div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.card')

@section('header')
Product # {{ $product->id }}
@endsection

@section('body')
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Owner</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{ $product->id }}</th>
            <td>{{ $product->name }}</td>
            <td>{{ $product->price }}</td>
            <td>{{ $product->user->name }}</td>
            <td>
                @can('update', $product)
                <a class="btn btn-primary btn-sm"
                    href="{{ route('products.edit', ['product' => $product]) }}"
                    role="button">Edit</a>
                @endcan
                @can('delete', $product)
                <button type="submit" form="delete"
                    formaction="{{ route('products.destroy', ['product' => $product]) }}"
                    class="btn btn-danger btn-sm ml-4">Delete</button>
                @endcan
            </td>
        </tr>
    </tbody>
</table>

<form id="delete" method="POST">
    @csrf
    @method('DELETE')
</form>
@endsection